# This is a basic workflow to help you get started with Actions
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - release-please*
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Starting github action...."

      - name: Setup env variables
        run: env

