# This is a basic workflow to help you get started with Actions
name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches: [main]

jobs:
  ci:
    if: ${{ ! startsWith(github.head_ref, 'release-please') || github.event.type != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Starting github action...."

      - name: Setup env variables
        run: env

