# This is a basic workflow to help you get started with Actions
name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

  push:
    branches:
      - main

jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, '#skip-ci') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup env variables
        run: |
          echo $GITHUB_ENV
          export

